ASM=nasm

SRC_DIR=src
BUILD_DIR=build
ASM_DIR=$(BUILD_DIR)/asm
OS_FILE=OS.img
asmfile = $(BUILD_DIR)/bootSector.bin \
		  $(BUILD_DIR)/2ndStage.bin \
		  $(BUILD_DIR)/fileTable.bin

all:
	rm -rf build || true
	make run
	
run: $(OS_FILE)
	@qemu-system-i386 -drive format=raw,file=$<,if=ide,index=0,media=disk


$(BUILD_DIR)/%.bin: $(SRC_DIR)/%.asm
	mkdir -p build/asm/
	$(ASM) $< -f bin -o $@

$(OS_FILE): $(asmfile)
	cat $^ > $(BUILD_DIR)/tmp.bin
	dd if=/dev/zero of=$@ bs=512 count=2880
	dd if=$(BUILD_DIR)/tmp.bin of=$@ conv=notrunc

